### ISSUE TITLE
docker-compose example is a little bit confusing

### ISSUE THREAD

**Issue by motey** [neechbear/tiddlywiki#12]
Hi there, 
i am sure there is reason behind it, but i could not start via the docker-compose example. 

https://github.com/neechbear/tiddlywiki#docker-compose

There is a part missing of the compose file, a random port declared i dont know the purpose of and the volume deceleration is missing.

a more helpful example would be

```yaml
version: "3.9"
services:
  tiddlywiki:
    container_name: tiddlywiki
    image: nicolaw/tiddlywiki
    volumes:
      - tiddlywiki:/home/diab/tiddlywiki_data_safe
    ports:
      - "8080:8080"
volumes:
  tiddlywiki: null
  ```
