### ISSUE TITLE
Update to 5.1.23

### ISSUE THREAD

**Issue by crosbyh** [neechbear/tiddlywiki#8]
Hello,

Would it be possible to merge the pull request to update the version in this container to 5.1.23?

Thank you!

**Comment by dudeskeeroo** [comment]
It looks like there isn't any action going on round these parts, so for any other Google wayfarers looking for a newer tiddly release with this docker image, you can do this with a docker build argument `TW_VERSION`.

If you are using `docker-compose`, you can add a `build` section to your config like this:

 ```
 tiddlywiki:
    container_name: tiddlywiki
    image: nicolaw/tiddlywiki
    build:
      context: https://github.com/neechbear/tiddlywiki.git
      args:
        TW_VERSION: 5.2.0
```
You can then build the image with 
`docker-compose build tiddlywiki`

Thanks for the repo, Nicola!
